# Generated by Django 3.0.8 on 2020-07-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foundation.choice',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foundation.question',),
        ),
    ]
